name: infra

on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Acción de Terraform a ejecutar'
        required: true
        default: 'plan'
        type: choice
        options:
          - 'plan'
          - 'apply'
          - 'destroy'
  push:
    branches:
      - main
    paths:
      - 'infra/**'
      - '.github/workflows/infra.yml'

permissions:
  id-token: write
  contents: read

jobs:
  terraform:
    name: 'Terraform Cloud Provisioning'
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: infra

    steps:
      - name: Checkout Código Fuente
        uses: actions/checkout@v4

      - name: Configurar Terraform CLI
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Terraform Format Check
        run: terraform fmt -check -diff

      - name: Terraform Init (Local Validation Mode)
        run: terraform init -backend=false

      - name: Terraform Validate
        run: terraform validate
